-- First production programme catalogue milestone: 100 current English-taught
-- programmes from official 2026/27 university catalogues. Catalogue presence is
-- separate from verified admission rules; every imported record remains unverified.

alter table public.programmes
  add column if not exists official_programme_code text,
  add column if not exists degree_class text,
  add column if not exists catalogue_source_url text,
  add column if not exists catalogue_checked_at date,
  add column if not exists duration_years numeric(3,1);

create unique index if not exists programmes_official_code_year_idx
  on public.programmes (university_id, official_programme_code, academic_year)
  where official_programme_code is not null;

with catalogue (
  university_slug, university_name, programme_name, city, degree_level,
  teaching_language, official_programme_code, degree_class, source_url
) as (
  values
    ('bologna', 'University of Bologna', 'Biology of Human and Environmental Health', 'Padova, Bologna', 'Bachelor', 'English', '5909', null, 'https://corsi.unibo.it/1cycle/HumanEnvironmentalHealth'),
    ('bologna', 'University of Bologna', 'Building Construction Engineering', 'Ravenna', 'Bachelor', 'English', '5897', null, 'https://corsi.unibo.it/1cycle/Building'),
    ('bologna', 'University of Bologna', 'Business and Economics', 'Bologna', 'Bachelor', 'English', '6609', null, 'https://corsi.unibo.it/1cycle/CLaBE'),
    ('bologna', 'University of Bologna', 'Economics and Finance', 'Bologna', 'Bachelor', 'English', '6646', null, 'https://corsi.unibo.it/1cycle/EconomicsFinance'),
    ('bologna', 'University of Bologna', 'Economics of Tourism and Cities', 'Rimini', 'Bachelor', 'English', '6054', null, 'https://corsi.unibo.it/1cycle/clet'),
    ('bologna', 'University of Bologna', 'Economics, Politics and Social Sciences', 'Bologna', 'Bachelor', 'English', '5819', null, 'https://corsi.unibo.it/1cycle/EconomicsPoliticsSocialSciences'),
    ('bologna', 'University of Bologna', 'European Studies', 'Bologna, Forlì', 'Bachelor', 'English', '5983', null, 'https://corsi.unibo.it/1cycle/EuropeanStudies'),
    ('bologna', 'University of Bologna', 'Genomics', 'Bologna', 'Bachelor', 'English', '6343', null, 'https://corsi.unibo.it/1cycle/Genomics'),
    ('bologna', 'University of Bologna', 'International Studies', 'Forlì', 'Bachelor', 'English', '5949', null, 'https://corsi.unibo.it/1cycle/InternationalStudies'),
    ('bologna', 'University of Bologna', 'Management and Economics', 'Forlì', 'Bachelor', 'English', '5892', null, 'https://corsi.unibo.it/1cycle/Management'),
    ('bologna', 'University of Bologna', 'Medicine and Surgery', 'Bologna', 'Single-cycle', 'English', '6264', null, 'https://corsi.unibo.it/singlecycle/MedicineAndSurgery'),
    ('bologna', 'University of Bologna', 'Pharmacy', 'Rimini', 'Single-cycle', 'English', '5987', null, 'https://corsi.unibo.it/singlecycle/Pharmacy-Rimini'),
    ('bologna', 'University of Bologna', 'Veterinary Medicine', 'Ozzano dell''Emilia', 'Single-cycle', 'English', '6197', null, 'https://corsi.unibo.it/singlecycle/VeterinaryMedicine'),
    ('bologna', 'University of Bologna', 'Advanced Automotive Engineering', 'Modena, Bologna', 'Master', 'English', '9239', null, 'https://corsi.unibo.it/2cycle/AutomotiveEngineering'),
    ('bologna', 'University of Bologna', 'Advanced Cosmetic Sciences', 'Rimini', 'Master', 'English', '6755', null, 'https://corsi.unibo.it/2cycle/AdvancedCosmeticSciences'),
    ('bologna', 'University of Bologna', 'Advanced Methods in Particle Physics', 'Bologna, Clermont-Ferrand, Dortmund', 'Master', 'English', '6694', null, 'https://corsi.unibo.it/2cycle/ParticlePhysics'),
    ('bologna', 'University of Bologna', 'Advanced Spectroscopy in Chemistry', 'Bologna', 'Master', 'English', '6790', null, 'https://corsi.unibo.it/2cycle/AdvancedSpectroscopyChemistry'),
    ('bologna', 'University of Bologna', 'Aerospace Engineering', 'Forlì', 'Master', 'English', '6704', null, 'https://corsi.unibo.it/2cycle/AerospaceEngineering'),
    ('bologna', 'University of Bologna', 'Applied Economics and Markets', 'Bologna', 'Master', 'English', '6756', null, 'https://corsi.unibo.it/2cycle/AppliedEconomicsMarkets'),
    ('bologna', 'University of Bologna', 'Architecture and Creative Practices for the City and Landscape', 'Bologna', 'Master', 'English', '6727', null, 'https://corsi.unibo.it/2cycle/ArchitectureCreativePractices'),
    ('bologna', 'University of Bologna', 'Artificial Intelligence', 'Bologna', 'Master', 'English', '6700', null, 'https://corsi.unibo.it/2cycle/artificial-intelligence'),
    ('bologna', 'University of Bologna', 'Astrophysics and Cosmology', 'Bologna', 'Master', 'English', '6765', null, 'https://corsi.unibo.it/2cycle/Astrophysics'),
    ('bologna', 'University of Bologna', 'Automation Engineering', 'Bologna', 'Master', 'English', '6711', null, 'https://corsi.unibo.it/2cycle/AutomationEngineering'),
    ('bologna', 'University of Bologna', 'Bioinformatics', 'Bologna', 'Master', 'English', '6767', null, 'https://corsi.unibo.it/2cycle/Bioinformatics'),
    ('bologna', 'University of Bologna', 'Biomedical Engineering', 'Cesena', 'Master', 'English', '6705', null, 'https://corsi.unibo.it/2cycle/BiomedicalEngineering'),
    ('bologna', 'University of Bologna', 'Business Administration and Sustainability', 'Forlì', 'Master', 'English', '6797', null, 'https://corsi.unibo.it/2cycle/BusinessAdministration-Forli'),
    ('bologna', 'University of Bologna', 'Chemical Innovation and Regulation', 'Bologna', 'Master', 'English', '6754', null, 'https://corsi.unibo.it/2cycle/ChemicalInnovationRegulation'),
    ('bologna', 'University of Bologna', 'Chemical Innovation and Regulation for Sustainability', 'Bologna', 'Master', 'English', '6258', null, 'https://corsi.unibo.it/2cycle/ChemicalInnovationRegulation'),
    ('bologna', 'University of Bologna', 'Civil Engineering', 'Bologna', 'Master', 'English', '6708', null, 'https://corsi.unibo.it/2cycle/CivilEngineering'),
    ('bologna', 'University of Bologna', 'Communications Engineering', 'Bologna', 'Master', 'English', '6712', null, 'https://corsi.unibo.it/2cycle/TelecommunicationsEngineering'),
    ('bologna', 'University of Bologna', 'Digital Humanities and Digital Knowledge', 'Bologna', 'Master', 'English', '6736', null, 'https://corsi.unibo.it/2cycle/DigitalHumanitiesKnowledge'),
    ('bologna', 'University of Bologna', 'Digital Minds', 'Bologna', 'Master', 'English', '6246', null, 'https://corsi.unibo.it/2cycle/DigitalMinds'),
    ('bologna', 'University of Bologna', 'Digital Transformation Management', 'Cesena, Forlì', 'Master', 'English', '6823', null, 'https://corsi.unibo.it/2cycle/DigitalTransformationManagement'),
    ('bologna', 'University of Bologna', 'East European and Eurasian Studies', 'Forlì', 'Master', 'English', '6751', null, 'https://corsi.unibo.it/2cycle/mirees'),
    ('bologna', 'University of Bologna', 'Economics and Econometrics', 'Bologna', 'Master', 'English', '6757', null, 'https://corsi.unibo.it/2cycle/lmec'),
    ('bologna', 'University of Bologna', 'Economics and Public Policy', 'Bologna', 'Master', 'English', '6758', null, 'https://corsi.unibo.it/2cycle/EconomicsPolicy'),
    ('bologna', 'University of Bologna', 'Electric Vehicle Engineering', 'Bologna', 'Master', 'English', '6713', null, 'https://corsi.unibo.it/2cycle/ElectricVehicleEngineering'),
    ('bologna', 'University of Bologna', 'Electronic Engineering for Intelligent Vehicles', 'Parma, Bologna, Modena', 'Master', 'English', '5917', null, 'https://corsi.unibo.it/2cycle/ElectronicEngineeringIntelligentVehicles'),
    ('bologna', 'University of Bologna', 'Engineering for Historic Building Rehabilitation', 'Ravenna', 'Master', 'English', '6710', null, 'https://corsi.unibo.it/2cycle/EngineeringProcessesSystems'),
    ('bologna', 'University of Bologna', 'Fashion Studies', 'Rimini', 'Master', 'English', '6780', null, 'https://corsi.unibo.it/2cycle/FashionStudies'),
    ('sapienza', 'Sapienza University of Rome', 'Product and Service Design', 'Rome', 'Master', 'English', '33433', 'LM-12', 'https://corsidilaurea.uniroma1.it/en/course/33433'),
    ('sapienza', 'Sapienza University of Rome', 'Economics and communication for management and innovation', 'Rome', 'Master', 'English', '33444', 'LM-77', 'https://corsidilaurea.uniroma1.it/en/course/33444'),
    ('sapienza', 'Sapienza University of Rome', 'Health Economics', 'Rome', 'Master', 'English', '33441', 'LM-56', 'https://corsidilaurea.uniroma1.it/en/course/33441'),
    ('sapienza', 'Sapienza University of Rome', 'Applied Computer Science and Artificial Intelligence', 'Rome', 'Bachelor', 'English', '33502', 'L-31', 'https://corsidilaurea.uniroma1.it/en/course/33502'),
    ('sapienza', 'Sapienza University of Rome', 'Engineering in Computer Science and Artificial Intelligence', 'Rome', 'Master', 'English', '33515', 'LM-32', 'https://corsidilaurea.uniroma1.it/en/course/33515'),
    ('sapienza', 'Sapienza University of Rome', 'Telecommunication Engineering', 'Rome', 'Master', 'English', '33510', 'LM-27', 'https://corsidilaurea.uniroma1.it/en/course/33510'),
    ('sapienza', 'Sapienza University of Rome', 'Artificial Intelligence', 'Rome', 'Master', 'English', '33513', 'LM-32', 'https://corsidilaurea.uniroma1.it/en/course/33513'),
    ('sapienza', 'Sapienza University of Rome', 'Bioinformatics', 'Rome', 'Bachelor', 'English', '33455', 'L-2', 'https://corsidilaurea.uniroma1.it/en/course/33455'),
    ('sapienza', 'Sapienza University of Rome', 'Computer Science', 'Rome', 'Master', 'English', '33508', 'LM-18', 'https://corsidilaurea.uniroma1.it/en/course/33508'),
    ('sapienza', 'Sapienza University of Rome', 'Artificial Intelligence and Robotics', 'Rome', 'Master', 'English', '33514', 'LM-32', 'https://corsidilaurea.uniroma1.it/en/course/33514'),
    ('sapienza', 'Sapienza University of Rome', 'Control Engineering', 'Rome', 'Master', 'English', '33509', 'LM-25', 'https://corsidilaurea.uniroma1.it/en/course/33509'),
    ('sapienza', 'Sapienza University of Rome', 'Cybersecurity', 'Rome', 'Master', 'English', '33516', 'LM-66', 'https://corsidilaurea.uniroma1.it/en/course/33516'),
    ('sapienza', 'Sapienza University of Rome', 'Data Science', 'Rome', 'Master', 'English', '33519', 'LM-Data', 'https://corsidilaurea.uniroma1.it/en/course/33519'),
    ('sapienza', 'Sapienza University of Rome', 'Sustainable Building Engineering (Rieti Campus)', 'Rome', 'Bachelor', 'English', '33482', 'L-23', 'https://corsidilaurea.uniroma1.it/en/course/33482'),
    ('sapienza', 'Sapienza University of Rome', 'Transport Systems Engineering', 'Rome', 'Master', 'English', '34180', 'LM-23', 'https://corsidilaurea.uniroma1.it/en/course/34180'),
    ('sapienza', 'Sapienza University of Rome', 'Environmental and Sustainable Building Engineering (Rieti Campus)', 'Rome', 'Master', 'English', '33489', 'LM-24', 'https://corsidilaurea.uniroma1.it/en/course/33489'),
    ('sapienza', 'Sapienza University of Rome', 'Sustainable Transportation and Electric Power Systems', 'Rome', 'Master', 'English', '34096', 'LM-28', 'https://corsidilaurea.uniroma1.it/en/course/34096'),
    ('sapienza', 'Sapienza University of Rome', 'Global Humanities', 'Rome', 'Bachelor', 'English', '33537', 'L-42', 'https://corsidilaurea.uniroma1.it/en/course/33537'),
    ('sapienza', 'Sapienza University of Rome', 'Classics', 'Rome', 'Bachelor', 'English', '33528', 'L-10', 'https://corsidilaurea.uniroma1.it/en/course/33528'),
    ('sapienza', 'Sapienza University of Rome', 'English and Anglo-American Studies', 'Rome', 'Master', 'English', '33548', 'LM-37', 'https://corsidilaurea.uniroma1.it/en/course/33548'),
    ('sapienza', 'Sapienza University of Rome', 'Cultural Heritage in the Near and Middle East, and in Africa', 'Rome', 'Master', 'English', '33541', 'LM-2', 'https://corsidilaurea.uniroma1.it/en/course/33541'),
    ('sapienza', 'Sapienza University of Rome', 'Mediterranean Archaeology', 'Rome', 'Master', 'English', '33542', 'LM-2', 'https://corsidilaurea.uniroma1.it/en/course/33542'),
    ('sapienza', 'Sapienza University of Rome', 'Fashion theory and practices - delivered in blended mode', 'Rome', 'Master', 'English', '33553', 'LM-65', 'https://corsidilaurea.uniroma1.it/en/course/33553'),
    ('sapienza', 'Sapienza University of Rome', 'Archaeological Materials Science', 'Rome', 'Master', 'English', '33600', 'LM-11', 'https://corsidilaurea.uniroma1.it/en/course/33600'),
    ('sapienza', 'Sapienza University of Rome', 'Biochemistry', 'Rome', 'Master', 'English', '33459', 'LM-9', 'https://corsidilaurea.uniroma1.it/en/course/33459'),
    ('sapienza', 'Sapienza University of Rome', 'Molecular Biology, Medicinal Chemistry and Computer Science for Pharmaceutical Applications', 'Rome', 'Bachelor', 'English', '33457', 'L-29', 'https://corsidilaurea.uniroma1.it/en/course/33457'),
    ('sapienza', 'Sapienza University of Rome', 'Medicine and Surgery  "F"', 'Rome', 'Master', 'English', '33454', 'LM-41', 'https://corsidilaurea.uniroma1.it/en/course/33454'),
    ('sapienza', 'Sapienza University of Rome', 'Dentistry and Dental Prosthodontics', 'Rome', 'Master', 'English', '33563', 'LM-46', 'https://corsidilaurea.uniroma1.it/en/course/33563'),
    ('sapienza', 'Sapienza University of Rome', 'Nursing - Roma Azienda Ospedaliera Sant’Andrea', 'Rome', 'Single-cycle', 'English', '28614', 'L/SNT1', 'https://corsidilaurea.uniroma1.it/en/course/28614'),
    ('sapienza', 'Sapienza University of Rome', 'Cognitive neuroscience', 'Rome', 'Master', 'English', '33574', 'LM-51', 'https://corsidilaurea.uniroma1.it/en/course/33574'),
    ('padova', 'University of Padua', 'Animal care', 'Padua', 'Bachelor', 'English', null, null, 'https://www.unipd.it/en/corsi-di-laurea/animal-care'),
    ('padova', 'University of Padua', 'Psychological science', 'Padua', 'Bachelor', 'English', null, null, 'https://www.unipd.it/en/corsi-di-laurea/psychological-science'),
    ('padova', 'University of Padua', 'Techniques and methods in psychological science', 'Padua', 'Bachelor', 'English', null, null, 'https://www.unipd.it/en/corsi-di-laurea/techniques-and-methods-psychological-science'),
    ('padova', 'University of Padua', 'Information Engineering', 'Padua', 'Bachelor', 'English', null, null, 'https://www.unipd.it/en/corsi-di-laurea/information-engineering'),
    ('padova', 'University of Padua', 'Italian Medieval and Renaissance studies', 'Padua', 'Bachelor', 'English', null, null, 'https://www.unipd.it/en/corsi-di-laurea/italian-medieval-and-renaissance-studies'),
    ('padova', 'University of Padua', 'Biology of Human and Environmental Health', 'Padua', 'Bachelor', 'English', null, null, 'https://www.unipd.it/en/corsi-di-laurea/biology-human-and-environmental-health'),
    ('padova', 'University of Padua', 'Earth and Climate Dynamics', 'Padua', 'Bachelor', 'English', null, null, 'https://www.unipd.it/en/corsi-di-laurea/earth-and-climate-dynamics'),
    ('padova', 'University of Padua', 'Economics, Governance and Decision-Making', 'Padua', 'Bachelor', 'English', null, null, 'https://www.unipd.it/en/corsi-di-laurea/economics-governance-and-decision-making'),
    ('padova', 'University of Padua', 'Medicine and Surgery - MedTech', 'Padua', 'Single-cycle', 'English', null, null, 'https://www.unipd.it/en/corsi-di-laurea/medicine-and-surgery-medtech'),
    ('padova', 'University of Padua', 'Medicine and Surgery', 'Padua', 'Single-cycle', 'English', null, null, 'https://www.unipd.it/en/corsi-di-laurea/medicine-and-surgery'),
    ('padova', 'University of Padua', 'Biotechnologies for food science', 'Padua', 'Master', 'English', null, null, 'https://www.unipd.it/en/corsi-di-laurea/biotechnologies-food-science'),
    ('padova', 'University of Padua', 'Forest sciences', 'Padua', 'Master', 'English', null, null, 'https://www.unipd.it/en/corsi-di-laurea/forest-sciences'),
    ('padova', 'University of Padua', 'Food and Health', 'Padua', 'Master', 'English', null, null, 'https://www.unipd.it/en/corsi-di-laurea/food-and-health'),
    ('padova', 'University of Padua', 'Food, Nutrition and Health', 'Padua', 'Master', 'English', null, null, 'https://www.unipd.it/en/corsi-di-laurea/food-nutrition-and-health'),
    ('padova', 'University of Padua', 'Italian food and wine', 'Padua', 'Master', 'English', null, null, 'https://www.unipd.it/en/corsi-di-laurea/italian-food-and-wine'),
    ('padova', 'University of Padua', 'Sustainable agriculture', 'Padua', 'Master', 'English', null, null, 'https://www.unipd.it/en/corsi-di-laurea/sustainable-agriculture'),
    ('padova', 'University of Padua', 'Environmental sciences for the ecological transition', 'Padua', 'Master', 'English', null, null, 'https://www.unipd.it/en/corsi-di-laurea/environmental-sciences-ecological-transition'),
    ('padova', 'University of Padua', 'Viticulture, Enology and Wine Marketing', 'Padua', 'Master', 'English', null, null, 'https://www.unipd.it/en/corsi-di-laurea/viticulture-enology-and-wine-marketing'),
    ('padova', 'University of Padua', 'Management for Sustainable Firms', 'Padua', 'Master', 'English', null, null, 'https://www.unipd.it/en/corsi-di-laurea/management-sustainable-firms'),
    ('padova', 'University of Padua', 'Accounting, Finance and Business Consulting', 'Padua', 'Master', 'English', null, null, 'https://www.unipd.it/en/corsi-di-laurea/accounting-finance-and-business-consulting'),
    ('padova', 'University of Padua', 'Applied Economics', 'Padua', 'Master', 'English', null, null, 'https://www.unipd.it/en/corsi-di-laurea/applied-economics'),
    ('padova', 'University of Padua', 'European and Global Studies', 'Padua', 'Master', 'English', null, null, 'https://www.unipd.it/en/corsi-di-laurea/european-and-global-studies'),
    ('padova', 'University of Padua', 'Human Rights and Multi-level Governance', 'Padua', 'Master', 'English', null, null, 'https://www.unipd.it/en/corsi-di-laurea/human-rights-and-multi-level-governance'),
    ('padova', 'University of Padua', 'Aerospace Engineering', 'Padua', 'Master', 'English', null, null, 'https://www.unipd.it/en/corsi-di-laurea/aerospace-engineering'),
    ('padova', 'University of Padua', 'Chemical and process engineering', 'Padua', 'Master', 'English', null, null, 'https://www.unipd.it/en/corsi-di-laurea/chemical-and-process-engineering'),
    ('padova', 'University of Padua', 'Computer Engineering', 'Padua', 'Master', 'English', null, null, 'https://www.unipd.it/en/corsi-di-laurea/computer-engineering'),
    ('padova', 'University of Padua', 'Cybersecurity', 'Padua', 'Master', 'English', null, null, 'https://www.unipd.it/en/corsi-di-laurea/cybersecurity'),
    ('padova', 'University of Padua', 'Control Systems Engineering', 'Padua', 'Master', 'English', null, null, 'https://www.unipd.it/en/corsi-di-laurea/control-systems-engineering'),
    ('padova', 'University of Padua', 'Electrical Engineering', 'Padua', 'Master', 'English', null, null, 'https://www.unipd.it/en/corsi-di-laurea/electrical-engineering'),
    ('padova', 'University of Padua', 'Electronic Engineering', 'Padua', 'Master', 'English', null, null, 'https://www.unipd.it/en/corsi-di-laurea/electronic-engineering')
)
insert into public.programmes (
  university_id, university_name, programme_name, country_code, city,
  degree_level, teaching_language, intake, source_url, application_url,
  academic_year, verification_status, verification_notes, requirements,
  official_programme_code, degree_class, catalogue_source_url,
  catalogue_checked_at, duration_years
)
select
  university.id,
  catalogue.university_name,
  catalogue.programme_name,
  'IT',
  catalogue.city,
  catalogue.degree_level,
  catalogue.teaching_language,
  'Fall 2026',
  catalogue.source_url,
  catalogue.source_url,
  '2026/27',
  'unverified',
  'Official catalogue entry. Admission requirements, fees and deadlines still require human verification against the programme call.',
  '{}'::jsonb,
  catalogue.official_programme_code,
  catalogue.degree_class,
  catalogue.source_url,
  date '2026-09-23',
  case catalogue.degree_level when 'Bachelor' then 3 when 'Master' then 2 else null end
from catalogue
join public.universities university on university.slug = catalogue.university_slug
on conflict (university_name, programme_name, academic_year) do update set
  university_id = excluded.university_id,
  city = excluded.city,
  degree_level = excluded.degree_level,
  teaching_language = excluded.teaching_language,
  source_url = excluded.source_url,
  application_url = excluded.application_url,
  official_programme_code = excluded.official_programme_code,
  degree_class = excluded.degree_class,
  catalogue_source_url = excluded.catalogue_source_url,
  catalogue_checked_at = excluded.catalogue_checked_at,
  duration_years = excluded.duration_years,
  updated_at = now();

comment on column public.programmes.catalogue_checked_at is
  'Date the programme presence and basic catalogue metadata were checked; this does not verify admission rules.';
